// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gjhhzudeactglbcmesdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqaGh6dWRlYWN0Z2xiY21lc2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTA1OTcsImV4cCI6MjA2ODQyNjU5N30.tmpmi8-BL7xHoXA1FG84ZaI0l9_bJlgisRlIU6X_dI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);